language: node_js
node_js:
  - '11.1.0'


branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  -npm install bootstrap
  - npm install -g yarn

script:
  - yarn build --base-href https://leoassuncao.github.io/github-pages/
  
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local_dir: dist
  on:
    branch: master
